# Write a simple github action to run the tests
name: Environment Setup & Tests

# This means that the action will run on every push and pull request
# on: [push, pull_request]
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master]

# Each workflow is made up of one or more jobs. Each job is a set of steps that are run sequentially
# The job is run on a fresh instance of the virtual environment
jobs:
  # This job sets up the environment and runs the tests
  setup_ubuntu:
    name: Setup Linux Environment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The steps that the job will run
    steps:
      # An action is a piece of code that performs one single task
      # uses keyword is used to specify the action
      # This action checks out the repository to the runner
      # Actions are stored in the .github/actions directory
      # The checkout action is stored in the actions/checkout repository
      # The v2 tag specifies the version of the action
      - uses: actions/checkout@v2
      # This action sets up python on the runner
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # This action installs the dependencies
      - name: Install dependencies
        # The run keyword is used to specify the command to run
        # The command is run in the default shell
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      # This action runs the tests
      - name: Show environment variables
        run: |
          env | sort
      - name: Run pytests
        run: |
          source venv/bin/activate
          python -m pytest tests.py

  # This job sets up the environment and runs the tests
  setup_windows:
    name: Setup Windows Environment
    # The type of runner that the job will run on
    runs-on: windows-latest
    # The steps that the job will run
    steps:
      # An action is a piece of code that performs one single task
      # uses keyword is used to specify the action
      # This action checks out the repository to the runner
      # Actions are stored in the .github/actions directory
      # The checkout action is stored in the actions/checkout repository
      # The v2 tag specifies the version of the action
      - uses: actions/checkout@v2
      # This action sets up python on the runner
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # This action installs the dependencies
      - name: Install dependencies
        # The run keyword is used to specify the command to run
        # The command is run in the default shell
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # This action runs the tests
      - name: Show environment variables
        run: |
          "Get-ChildItem Env: | Sort-Object Name"
      - name: Run pytests
        run: |
          venv\Scripts\activate
          python -m pytest tests.py

  # Run python tests on after setting up the environment
  run_pytest_ubuntu:
    name: Run Pytest Ubuntu
    runs-on: ubuntu-latest
    needs: setup_ubuntu
    steps:
      - name: Ubuntu Message
        run: |
          echo "Testing and env setup on ubuntu complete"

  # Run python tests on after setting up the environment
  run_pytest_windows:
    name: Run Pytest Windows
    runs-on: windows-latest
    needs: setup_windows
    steps:
      - name: Windows Message
        run: |
          echo "Testing and env setup on windows complete"
